version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Instalando dependencias"
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Empaquetando aplicación"
      - zip -r app.zip . -x "*.git*" "*.gitignore" "*__pycache__*"
artifacts:
  files:
    - app.zip