version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo "Instalando dependencias para validar"
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Empaquetando solo archivos del repositorio"
      - zip -r app.zip . -x "*.git*" "*__pycache__*" "*.pyc" "*.pyo" "*.dist-info*" "*.egg-info*" ".venv*" "package*" "venv*" "build*" "*.log"
artifacts:
  files:
    - app.zip